
npr_dict= { 'afghanistan' : 1149,
                'africa' : 1126,
                'asia' : 1125,
                'economy' : 1017,
                'elections' : 139482413,
                'europe' : 1124,
                'israel' : 1101,
                'palestine' : 1101,
                'middle east' : 1009,
                'politics' : 1014,
                'us' : 1003,
                'world' : 1004
               }
nytsections = ['home',
                'world',
                'national',
                'politics',
                'nyregion',
                'business',
                'opinion',
                'technology',
                'science',
                'health',
                'sports',
                'arts',
                'fashion',
                'dining',
                'travel',
                'magazine',
                'realestate',
              ]

categories = {  'us':['politics','economy','elections','healthcare','abortion','guns','terrorism'],
                'africa':['somalia','zimbabwe','zika','ebola','robert mugabe', 'kenya', 'boko haram', 'nigeria', 'jacob zuma'],
                'asia':['china','north korea', 'south china sea', 'japan','india'],
                'world':[],
                'europe':['greece','spain','budget crisis','eu','europe debt','germany', 'angela merkel', 'francois hollande',
                          'iceland prime minister', 'britain', 'david cameron'],
                'middle east':['israel','palestine', 'libya', 'egypt', 'egypt christians', 'mahmoud abbas', 'iran','iran sanctions',
                               'saudia arabia', 'oil', 'isis', 'islamic state'],
                'americas':['peru','peru election','dilma rousseff', 'brazil','argentina','kirchner'],
                
             } 
