# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('url', models.URLField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
            ],
        ),
    ]
